apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: queues.scheduling.x-k8s.io
  annotations:
    "api-approved.kubernetes.io": "https://github.com/kube-queue/api/pull/1"
spec:
  group: scheduling.x-k8s.io
  names:
    kind: Queue
    plural: queues
    singular: queue
    shortNames:
      - queue
      - queues
  scope: Namespaced
  versions:
    - name: "v1alpha1"
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                queuePolicy:
                  type: string
                priority:
                  type: integer
                priorityClassName:
                  type: string
                  additionalProperties:
                    anyOf:
                      - type: integer
                      - type: string
                    pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                    x-kubernetes-int-or-string: true
            status: