// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// QueueUnitListerExpansion allows custom methods to be added to
// QueueUnitLister.
type QueueUnitListerExpansion interface{}

// QueueUnitNamespaceListerExpansion allows custom methods to be added to
// QueueUnitNamespaceLister.
type QueueUnitNamespaceListerExpansion interface{}
