// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/kube-queue/api/pkg/apis/scheduling/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeQueueUnits implements QueueUnitInterface
type FakeQueueUnits struct {
	Fake *FakeSchedulingV1alpha1
	ns   string
}

var queueunitsResource = schema.GroupVersionResource{Group: "scheduling.x-k8s.io", Version: "v1alpha1", Resource: "queueunits"}

var queueunitsKind = schema.GroupVersionKind{Group: "scheduling.x-k8s.io", Version: "v1alpha1", Kind: "QueueUnit"}

// Get takes name of the queueUnit, and returns the corresponding queueUnit object, and an error if there is any.
func (c *FakeQueueUnits) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.QueueUnit, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(queueunitsResource, c.ns, name), &v1alpha1.QueueUnit{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.QueueUnit), err
}

// List takes label and field selectors, and returns the list of QueueUnits that match those selectors.
func (c *FakeQueueUnits) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.QueueUnitList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(queueunitsResource, queueunitsKind, c.ns, opts), &v1alpha1.QueueUnitList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.QueueUnitList{ListMeta: obj.(*v1alpha1.QueueUnitList).ListMeta}
	for _, item := range obj.(*v1alpha1.QueueUnitList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested queueUnits.
func (c *FakeQueueUnits) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(queueunitsResource, c.ns, opts))

}

// Create takes the representation of a queueUnit and creates it.  Returns the server's representation of the queueUnit, and an error, if there is any.
func (c *FakeQueueUnits) Create(ctx context.Context, queueUnit *v1alpha1.QueueUnit, opts v1.CreateOptions) (result *v1alpha1.QueueUnit, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(queueunitsResource, c.ns, queueUnit), &v1alpha1.QueueUnit{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.QueueUnit), err
}

// Update takes the representation of a queueUnit and updates it. Returns the server's representation of the queueUnit, and an error, if there is any.
func (c *FakeQueueUnits) Update(ctx context.Context, queueUnit *v1alpha1.QueueUnit, opts v1.UpdateOptions) (result *v1alpha1.QueueUnit, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(queueunitsResource, c.ns, queueUnit), &v1alpha1.QueueUnit{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.QueueUnit), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeQueueUnits) UpdateStatus(ctx context.Context, queueUnit *v1alpha1.QueueUnit, opts v1.UpdateOptions) (*v1alpha1.QueueUnit, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(queueunitsResource, "status", c.ns, queueUnit), &v1alpha1.QueueUnit{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.QueueUnit), err
}

// Delete takes name of the queueUnit and deletes it. Returns an error if one occurs.
func (c *FakeQueueUnits) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(queueunitsResource, c.ns, name), &v1alpha1.QueueUnit{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeQueueUnits) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(queueunitsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.QueueUnitList{})
	return err
}

// Patch applies the patch and returns the patched queueUnit.
func (c *FakeQueueUnits) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.QueueUnit, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(queueunitsResource, c.ns, name, pt, data, subresources...), &v1alpha1.QueueUnit{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.QueueUnit), err
}
